import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import * as schema from "../../src/api/database/schema";

/**
 * Test database — a fresh throwaway libsql instance per suite, built from the same generated
 * migration the real Turso database is pushed from. No test ever touches the live database.
 *
 * Each instance is a temp FILE, not `:memory:`. `@libsql/client` opens a separate connection for
 * an interactive transaction, and with `:memory:` that connection is a different, empty database —
 * so anything running through `withScopedTransaction` sees no tables and then poisons the client
 * for every later query. See tests/helpers/preload.ts for the full write-up.
 */

const DRIZZLE_DIR = new URL("../../drizzle/", import.meta.url).pathname;

function migrationSql(): string {
  const files = readdirSync(DRIZZLE_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  if (files.length === 0) {
    throw new Error("No migration found in packages/web/drizzle — run `bun run db:generate` first.");
  }
  return files.map((f) => readFileSync(join(DRIZZLE_DIR, f), "utf8")).join("\n--> statement-breakpoint\n");
}

/**
 * The migration as individual statements.
 *
 * Exported because the module-level client needs the same schema (see module-db.ts): anything
 * that queries through `scopedDb()` with no explicit database — tenant/resolve.ts, Better Auth —
 * hits that connection, not a per-suite one.
 *
 * NOTE: these files are only regenerated by `bun run db:generate`. `db:push` writes to Turso
 * WITHOUT touching them, so a push-only schema change silently drifts the test database out of
 * sync with the real one. Always run both.
 */
export function migrationStatements(): string[] {
  return migrationSql()
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

export type TestDb = ReturnType<typeof drizzle<typeof schema>>;

export async function createTestDb(): Promise<TestDb> {
  const dir = mkdtempSync(join(tmpdir(), "b2b-suite-db-"));
  process.on("exit", () => rmSync(dir, { recursive: true, force: true }));

  const client = createClient({ url: `file:${join(dir, "suite.db")}` });
  for (const sql of migrationStatements()) {
    await client.execute(sql);
  }
  return drizzle(client, { schema });
}
